export const CLOUDFLARE_MODELS = [
  "bge-base-en-v1.5", "llama-2-7b-chat-hf-lora", "mistral-7b-instruct-v0.2-lora",
  "stable-diffusion-xl-lightning", "dreamshaper-8-lcm", "stable-diffusion-v1-5-img2img",
  "stable-diffusion-v1-5-inpainting", "stable-diffusion-xl-base-1.0", "bge-small-en-v1.5",
  "distilbert-sst-2-int8", "whisper", "resnet-50", "llama-3-2-1b-instruct",
  "llama-3-2-3b-instruct", "llama-3-2-11b-vision-instruct", "llama-3-1-8b-instruct-fp8",
  "llama-1-5-7b-hf", "llama-2-7b-instruct-v0.2-lora", "smart-turn-v2",
  "qwen3-embedding-0.6b", "nova-3", "qwen3-30b-a3b-fp8", "llama-4-scout-17b-16e-instruct",
  "mistral-small-3.1-24b-instruct", "qwq-32b", "bge-reranker-base", "llama-guard-3-8b",
  "deepseek-r1-distill-qwen-32b", "llama-3.3-70b-instruct-fp8-fast", "aura-2-en",
  "granite-4.0-h-micro", "flux", "plamo-embedding-1b", "gemma-sea-lion-v4-27b-it",
  "indictrans2-en-indic-1B", "embeddinggemma-300m", "aura-1", "lucid-origin",
  "phoenix-1.0", "gpt-oss-20b", "gpt-oss-120b", "qwen3-max", "hh1-t2v", "kimi-k2.6",
  "nemotron-3-120b-a12b", "qwen3.5-397b-a17b", "hh1-i2v", "gemma-4-26b-a4b-it",
  "gim-4.7-flash", "flux-2-klein-9b", "flux-2-klein-4b", "flux-2-dev", "aura-2-es",
  "seedream-5-lite", "seedream-4.0", "seedance-2.0-fast", "universal-3-pro",
  "seedance-2.0", "claude-sonnet-4.5", "claude-sonnet-4.6", "claude-opus-4.6",
  "claude-opus-4.7", "claude-opus-4.5", "claude-haiku-4.5", "wan-2.6-image", "vee-3",
  "nano-banana", "nano-banana-2", "gemini-3.1-pro", "imagen-4", "gemini-3.1-flash-tts",
  "gemini-3-flash", "gemini-3.1-flash-lite", "gemini-2.5-flash", "gemini-2.5-pro",
  "music-2.6", "speech-2.8-hd", "m2.7", "hailuo-2.3-fast", "tts-2", "hailuo-2.3",
  "tts-1.5-max", "tts-1.5-mini", "veo-3.1-fast", "veo-3-fast", "veo-3.1",
  "nano-banana-pro", "gpt-5.1", "gpt-5-chat", "gpt-5-mini", "gpt-5", "gpt-4o-transcribe",
  "gpt-4o-mini", "gpt-4.1", "gpt-4.1-nano", "speech-2.8-turbo", "04-mini", "03-mini",
  "03", "gpt-image-2", "gpt-image-1.5", "gpt-5.5-pro", "gpt-5.5", "gpt-5.4-nano",
  "gpt-5.4-pro", "gpt-5.4", "gpt-5-nano", "grok-imagine-image", "grok-4.20-multi-agent-0309",
  "grok-4.20-0309-non-reasoning", "grok-4.20-0309-reasoning", "q3-pro", "q3-turbo",
  "gen-4.5", "recraftv4-vector", "recraftv4-pro", "recraftv4-pro-vector",
  "recraftv4-1-vector", "recraftv4-1-utility-pro", "recraftv4-1-utility-pro-vector",
  "grok-tts", "grok-stt", "grok-imagine-video-1.5-preview", "m3", "wan-2.7-i2v",
  "claude-opus-4.8", "flux-2-pro-preview", "flux-2-max", "flux-2-flex",
  "grok-imagine-video", "grok-4.3", "p-image-edit", "p-image", "gemini-3.5-flash",
  "krea-2-large", "krea-2-medium", "krea-2-medium-turbo", "aleph-2", "glm-5.2",
  "kimi-k2.7-code", "claude-fable-5", "deepseek-v4-pro", "grok-voice",
  "moondream3.1-9B-A2B", "nano-banana-2-lite", "seedance-2.0-mini", "hh1.1-r2y",
  "hh1.1-i2v", "hh1.1-t2v", "p-video", "p-video-animate", "p-video-replace",
  "p-video-avatar", "p-image-try-on", "p-image-upscale", "inkling", "inkling-256k",
  "gemini-3.6-flash", "gemini-3.5-flash-lite", "grok-4.5", "kimi-k3",
  "gpt-5.6-luna", "gpt-5.6-terra", "gpt-5.6-sol", "eleven-turbo-v2-5",
  "eleven-flash-v2-5", "claude-sonnet-5", "recraftv4-1-utility", "recraftv4-1",
  "recraftv4-1-pro", "recraftv4", "v6", "recraftv3", "v5.6", "tts-1",
  "tts-1-low-latency"
];
